blueprint:
  name: HASPone bright up the backlight for a period when the touchscreen is touched
  description: '

    ## Blueprint Version: `1.05.00`


    # Description

    When the touchscreen is touched, the screen is lit for a period of time before
    returning to its defaut intensity

    '
  domain: automation
  input:
    haspdevice:
      name: HASPone Device
      description: Select the HASPone device
      selector:
        device:
          integration: mqtt
          manufacturer: HASwitchPlate
          model: HASPone v1.0.0
          multiple: false
    brightness:
      name: Active brightness value
      description: Select the brightness value to be set when screen is active.
      default: 100
      selector:
        number:
          min: 1.0
          max: 100.0
          mode: slider
          unit_of_measurement: '%'
          step: 1.0
    # duration_time:
    #   name: Duration of the brightness
    #   description: Select the duration of the brightness period in seconds
    #   selector:
    #     duration:
    #       default: "00:00:10"
  source_url: https://github.com/SylvainGa/HABlueprints/blob/hasp_bright_screen_on_touch_with_timer.yaml
mode: single
max_exceeded: silent
variables:
  haspdevice: !input haspdevice
  haspname: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{- entity|regex_replace(find=\"^sensor\\.\", replace=\"\", ignorecase=true)|regex_replace(find=\"_sensor(?:_\\d+|)$\",
    replace=\"\", ignorecase=true) -}}\n  {%- endif -%}\n{%- endfor -%}"
  haspsensor: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{ entity }}\n  {%- endif -%}\n{%- endfor -%}"
  new_brightness: !input brightness
#   duration_in_sec: !input duration_time
  old_new_brightness: '{{ state_attr(haspdevice, "brightness") | int(255) }}'
  lightcommandtopic: '{{ ''hasp/'' ~ haspname ~ ''/brightness/set'' }}'

trigger_variables:
  haspdevice: !input haspdevice
  haspname: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{- entity|regex_replace(find=\"^sensor\\.\", replace=\"\", ignorecase=true)|regex_replace(find=\"_sensor(?:_\\d+|)$\",
    replace=\"\", ignorecase=true) -}}\n  {%- endif -%}\n{%- endfor -%}"
  haspsensor: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{ entity }}\n  {%- endif -%}\n{%- endfor -%}"
  jsontopic: '{{ "hasp/" ~ haspname ~ "/state/json" }}'
  hasppage: !input hasppage
  haspbutton: !input haspbutton
  haspobject: '{{ "p[" ~ hasppage ~ "].b[" ~ haspbutton ~ "]" }}'
  buttonjsonpayload: '{"event_type":"button_short_press","event":"{{haspobject}}","value":"ON"}'

trigger:
- platform: mqtt
  topic: '{{jsontopic}}'
  payload: '{{buttonjsonpayload}}'
condition:
- condition: template
  value_template: '{{ is_state(haspsensor, ''ON'') }}'
action:
  - service: mqtt.publish
    data:
      topic: '{{ lightcommandtopic }}'
      payload: '{{ (brightness | int(255) }}'
#   - delay: '{{ duration_in_sec }}'

  - delay: '{{ "00:00:10" }}'

  - service: mqtt.publish
    data:
      topic: '{{ lightcommandtopic }}'
      payload: '{{ (old_new_brightness | int(255) }}'
