blueprint:
  name: HASPone Temporarely light the screen on activity
  description: '

    ## Blueprint Version: `1.00.00`


    # Description


    Temporarely light the screen on activity. Intensity retuens to its previous
    level after a period of time if all lights in our controlled group are off.

    '
  domain: automation
  input:
    haspdevice:
      name: HASPone Device
      description: Select the HASPone device
      selector:
        device:
          integration: mqtt
          manufacturer: HASwitchPlate
          model: HASPone v1.0.0
          multiple: false
    idletime:
      name: Idle Time
      description: Idle time in seconds
      default:
        hours: 0
        minutes: 0
        seconds: 10
      selector:
        duration:
    brightvalue:
      name: Brightness to set on activity
      description: Select the brightness value to become when activity is sensed.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: percent
          step: 1
    lightgroup:
      name: Group of lights to monitor
      description: Group of lights to monitor for activity. If the group is on, the
        dimming back is skipped
      selector:
        entity:
          domain:
          - group
          multiple: false
  source_url: https://github.com/SylvainGa/HABlueprints/blob/main/hasp_Dim_Screen_on_Idle_and_grouplight.yaml
mode: single
max_exceeded: silent
variables:
  haspdevice: !input haspdevice
  haspname: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{- entity|regex_replace(find=\"^sensor\\.\", replace=\"\", ignorecase=true)|regex_replace(find=\"_sensor(?:_\\d+|)$\",
    replace=\"\", ignorecase=true) -}}\n  {%- endif -%}\n{%- endfor -%}"
  brightness: !input brightvalue
  new_brightness: '{{(brightness * 255 / 100)|int}}'
  idletime: !input idletime
  lightcommandtopic: '{{ "hasp/" ~ haspname ~ "/brightness/set" }}'
  old_brightness: '{{ state_attr("light." ~ haspname ~ "_backlight", "brightness")|int }}'
trigger_variables:
  haspdevice: !input haspdevice
  haspname: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{- entity|regex_replace(find=\"^sensor\\.\", replace=\"\", ignorecase=true)|regex_replace(find=\"_sensor(?:_\\d+|)$\",
    replace=\"\", ignorecase=true) -}}\n  {%- endif -%}\n{%- endfor -%}"
  haspsensor: "{%- for entity in device_entities(haspdevice) -%}\n  {%- if entity|regex_search(\"^sensor\\..+_sensor(?:_\\d+|)$\")
    -%}\n    {{ entity }}\n  {%- endif -%}\n{%- endfor -%}"
  jsontopic: '{{ "hasp/" ~ haspname ~ "/state/json" }}'
trigger:
- platform: mqtt
  topic: '{{jsontopic}}'
# - platform: state
#   entity_id: !input lightgroup
#   to: 'off'
condition:
- condition: template
  value_template: '{{ is_state(haspsensor, ''ON'') }}'
- condition: and
  conditions:
  - condition: template
    value_template: '{{ ((trigger.payload_json.event_type is defined) and (trigger.payload_json.event_type
      == ''button_short_press'')) }}'
  - condition: state
    entity_id: !input lightgroup
    state: 'off'
action:
- service: mqtt.publish
  data:
    topic: '{{lightcommandtopic}}'
    payload: '{{new_brightness}}'
- delay: '{{idletime}}'
- condition: state
  entity_id: !input lightgroup
  state: 'off'
- service: mqtt.publish
  data:
    topic: '{{lightcommandtopic}}'
    payload: '{{old_brightness}}'
